version: "3"
services:
  # service configuration for our database
  database:

    # use the preferred version of the official Postgres image
    # see https://hub.docker.com/_/postgres/
    image: postgres:9.4.5

    # 2020-06-26 (asolera): Linha adicionada para padronizar o nome dos contêineres
    container_name: consul_database

    # persist the database between containers by storing it in a volume
    volumes:
      - /home/consul-database:/var/lib/postgresql/data

    # 2020-06-26 (asolera): Acrescentei opção para que o container sempre reinicie (caso o servidor seja reiniciado).
    restart: always

  # service configuration for our dockerized Rails app
  app:

    # use the Dockerfile next to this file

    # 2020-06-26 (asolera): Comentei a linha abaixo pois a cada execução dos scripts de banco,
    # ele estava buildando novamente a imagem Docker desnecessariamente. Ao invés disso,
    # acrescentei a outra linha contendo o nome da imagem gerada através do processo de build.
    # build: .
    image: consul-sgm

    # 2020-06-26 (asolera): Linha adicionada para padronizar o nome dos contêineres
    container_name: consul_app

    # 2020-06-26 (asolera): Comentei as linhas abaixo pois estavam causando erros de permissionamento nos arquivos,
    # causado pelo pull request https://github.com/consul/consul/pull/2661.
    # entrypoint: /usr/local/bin/entrypoint.sh
    # command: bundle exec rails s -p 3000 -b "0.0.0.0"
    # working_dir: /var/www/consul

    # makes the app container aware of the DB container
    depends_on:
      - database

    # 2020-06-26 (asolera): Acrescentei opção para que o container sempre reinicie (caso o servidor seja reiniciado).
    restart: always

    # expose the port we configured Unicorn to bind to
    ports:
      - "80:3000"
    # map our application source code, in full, to the application root of our container
    volumes:
      # 2020-06-26 (asolera): Substituí as linhas abaixo pois estavam causando erro ao rodar os containers, conforme visto
      # em https://github.com/consul/consul/issues/3588.
      # - .:/var/www/consul:delegated
      # - bundle:/usr/local/bundle:delegated
      # - "$SSH_AUTH_SOCK:/tmp/agent.sock"
      - "$PWD:/var/www/consul"
      - /home/consul-bundle:/usr/local/bundle
      - /tmp/agent.sock:/tmp/agent.sock
    environment:
      - SSH_AUTH_SOCK=/tmp/agent.sock
      - RAILS_ENV=production
