version: "3"
services:
  database:
    image: postgres:9.4.5
    container_name: consul_database
    restart: always
    volumes:
      - /home/consul-database:/var/lib/postgresql/data

  app:
    image: consul-sgm
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - "$PWD:/var/www/consul"
      - bundle:/usr/local/bundle
      - /tmp/agent.sock:/tmp/agent.sock
    environment:
      - SSH_AUTH_SOCK=/tmp/agent.sock
volumes:
  bundle: {}
